# Generated by Django 4.2.3 on 2023-07-22 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0002_remove_location_address_location_civic_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('[A-Z]\\d[A-Z]\\s\\d[A-Z]\\d')]),
        ),
    ]
