# Generated by Django 4.2.3 on 2023-07-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0003_alter_location_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=80.788),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=45.34),
            preserve_default=False,
        ),
    ]
