# Generated by Django 4.2.3 on 2023-07-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0006_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(default=2043, max_length=50),
            preserve_default=False,
        ),
    ]
