# Generated by Django 4.2.3 on 2024-01-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0007_location_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='grid',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
