# Generated by Django 4.2.3 on 2024-01-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0008_population_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='height',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='width',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
