# Generated by Django 4.2.3 on 2024-01-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0009_population_height_population_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='height',
        ),
        migrations.RemoveField(
            model_name='population',
            name='width',
        ),
    ]
