# Generated by Django 4.2.3 on 2024-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_counter', '0010_remove_population_height_remove_population_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='img_height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='population',
            name='img_width',
            field=models.IntegerField(default=1080),
        ),
    ]
